version: '3.3'
services:
  backend:
    image: dto80/se234-lab12
    ports:
      - 8082:8080 
    volumes:
      - type: bind
        source: /home/ubuntu/data
        target: /data
  forntend:
    image: thanaphat14/lab10.3
    ports:
      - 8080:80
